### ISSUE TITLE
model parsing issue

### ISSUE THREAD

**Issue by b3ll4t0r** [krakenjs/generator-swaggerize#12]
```
undefined:47
            body = models[param.schema.$ref.slice(param.schema.$ref.lastIndexO
                                                                    ^
TypeError: Cannot call method 'lastIndexOf' of undefined
    at eval (eval at template (/usr/local/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:6305:22), <anonymous>:47:77)
    at Function.forEach (/usr/local/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:3297:15)
    at eval (eval at template (/usr/local/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:6305:22), <anonymous>:29:15)
    at Function.forEach (/usr/local/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:3297:15)
    at eval (eval at template (/usr/local/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:6305:22), <anonymous>:16:3)
    at underscore [as _engine] (/usr/local/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/lib/util/engines.js:32:30)
    at engine (/usr/local/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/lib/actions/actions.js:303:10)
    at template (/usr/local/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/lib/actions/actions.js:281:15)
    at /usr/local/lib/node_modules/generator-swaggerize/app/index.js:347:18
    at Array.forEach (native)
```

**Comment by subeeshcbabu** [comment]
Closing as per #62
