### ISSUE TITLE
Can't start vanilla hapijs generated app.

### ISSUE THREAD

**Issue by totherik** [krakenjs/generator-swaggerize#22]
```shell
$ yo swaggerize
#...
$ cd <my dir>
$ node index.js 

module.js:340
    throw err;
          ^
Error: Cannot find module 'handlers/components.js'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at /Users/me/src/git/arbuckle/node_modules/swaggerize-hapi/node_modules/swaggerize-builder/lib/readhandlers.js:30:27
    at Array.forEach (native)
    at read (/Users/me/src/git/arbuckle/node_modules/swaggerize-hapi/node_modules/swaggerize-builder/lib/readhandlers.js:21:29)
    at buildroutes (/Users/me/src/git/arbuckle/node_modules/swaggerize-hapi/node_modules/swaggerize-builder/lib/buildroutes.js:16:16)
    at swaggerize (/Users/me/src/git/arbuckle/node_modules/swaggerize-hapi/node_modules/swaggerize-builder/lib/index.js:65:12)
    at Object.module.exports.register (/Users/me/src/git/arbuckle/node_modules/swaggerize-hapi/lib/index.js:30:18)
```

**Comment by tlivings** [comment]
Is this still occurring?

**Comment by totherik** [comment]
Haven't revisited.
