### ISSUE TITLE
Issue with allOf in swagger definitions

### ISSUE THREAD

**Issue by MrWako** [krakenjs/generator-swaggerize#8]
Hi Folks,

I've been looking at the V2 JSON examples in https://github.com/swagger-api/swagger-spec/tree/master/examples/v2.0/json and using them with the generator has created a few issues that I've tried to breakdown a little. The first is from https://github.com/swagger-api/swagger-spec/blob/master/examples/v2.0/json/petstore-simple.json

Take 2 copies of this file and delete the `"/pets/{id}": { ... }` sections. In one use the definition

```
"petInput": {
      "allOf": [
        {
          "$ref": "pet"
        }
      ]
    }
```

in the other use the definition

```
"petInput": {
      "required": [
        "id",
        "name"
      ],
      "properties": {
        "id": {
          "type": "integer",
          "format": "int64"
        },
        "name": {
          "type": "string"
        },
        "tag": {
          "type": "string"
        }
      }
    }
```

I find the one with the $ref generates:

```
Swaggerize Generator
? What would you like to call this project: ref
? Your name: 
? Your github user name: 
? Your email: 
? Path (or URL) to swagger document: ref.json
? Express or Hapi: express
   create .jshintrc
   create .gitignore
   create .npmignore
   create index.js
   create package.json
   create README.md
   create config/ref.json
   create handlers/pets.js

undefined:10
_.forEach(Object.keys(properties), function (prop) {;
                      ^
ReferenceError: properties is not defined
    at eval (eval at template (/node-v0.10.33-linux-x64/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/node_modules/lodash/dist/lodash.js:6305:22), <anonymous>:10:23)
    at underscore [as _engine] (/node-v0.10.33-linux-x64/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/lib/util/engines.js:32:30)
    at engine (/node-v0.10.33-linux-x64/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/lib/actions/actions.js:303:10)
    at template (/node-v0.10.33-linux-x64/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/lib/actions/actions.js:281:15)
    at /node-v0.10.33-linux-x64/lib/node_modules/generator-swaggerize/app/index.js:260:18
    at Array.forEach (native)
    at yeoman.generators.Base.extend.models (/node-v0.10.33-linux-x64/lib/node_modules/generator-swaggerize/app/index.js:249:49)
    at /node-v0.10.33-linux-x64/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/lib/base.js:341:43
    at /node-v0.10.33-linux-x64/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/node_modules/async/lib/async.js:551:21
    at /node-v0.10.33-linux-x64/lib/node_modules/generator-swaggerize/node_modules/yeoman-generator/node_modules/async/lib/async.js:227:13
```

node version v0.10.33, yeoman version 1.3.3. Latest version of generator-swaggerize.

**Comment by grawk** [comment]
Is this an issue with the enjoi module then? Or in `swaggerize-*` somewhere? Running into this now as well, and with `allOf` being a good way to DRY, it's a shame to not be able to use it...

**Comment by subeeshcbabu** [comment]
Following the `enjoi` docs - https://github.com/tlivings/enjoi#schema-support, `allOf` support got released as part of one of the recent versions. 

I am waiting for the a new publish of the `generator-swaggerize` version that includes my change of `enjoi` version upgrade. Will test this out as soon as the new generator gets published.

**Comment by subeeshcbabu** [comment]
https://github.com/krakenjs/generator-swaggerize/blob/master/app/templates/_model.js#L7
`models` template generator is expecting `properties` as opposed to the possibilities of `allOf` etc. I will on a PR for addressing this.

**Comment by mirchow** [comment]
This feature would be much appreciated.
Consider skipping generating of `allOf` models for now with a console warning. It would allow the rest of models to be generated.
This section can be added to your pets.json tests
```
       "Pets": {
            "type": "array",
            "items": {
                "$ref": "#/definitions/Pet"
            }
        },
        "Paging": {
            "properties": {
                "totalItems": {
                    "type": "integer"
                },
                "totalPages": {
                    "type": "integer"
                },
                "pageSize": {
                    "type": "integer"
                },
                "currentPage": {
                    "type": "integer"
                }
            }
        },
        "PagedPets": {
            "allOf": [
                {
                    "$ref": "#/definitions/Pets"
                },
                {
                    "$ref": "#/definitions/Paging"
                }
            ]
        },
```

**Comment by subeeshcbabu** [comment]
Please checkout the latest version `generator-swaggerize@3.0.0`. This should be resolved.
